name: ymm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Dubai
    fonts:
    - asset: fonts/Dubai-Medium.TTF
